name: Build/Release

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main

jobs:
  build_on_linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.14
      - name: Install Dependencies
        run: |
          sudo apt-get -y install rpm
          npm install
          npm install electron-installer-redhat electron-installer-debian
      - name: Build on Linux
        run: npm run build-linux
      - name: Package on Linux
        run: |
          npm run deb-amd64
          npm run deb-armhf
          npm run deb-arm64
          npm run rpm-x86_64
          npm run rpm-armhfp
          npm run rpm-aarch64
      - name: Check Output
        run: ls out/installers
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            out/installers/grafana-kiosk*
  build_on_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.14
      - name: Install Dependencies
        run: |
          npm install
          npm install macos-alias electron-installer-dmg
      - name: Build on MacOS
        run: npm run build-darwin
      - name: Package on MacOS
        run: |
          npm run darwin-x64
          npm run darwin-arm64
      - name: Check Output
        run: ls out/installers
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            out/installers/grafana-kiosk*
  build_on_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.14
      - name: Install Node Tools
        run: npm install --global --production node-gyp@latest
      - name: Install Dependencies
        run: |
          npm install
          npm install electron-installer-windows
      - name: Build on Windows
        run: npm run build-win
      - name: Package on Windows
        run: |
          npm run win-x64
          npm run win-arm64
      - name: Fix Filenames
        run: |
          Get-ChildItem .\out\installers\x64\* -Exclude RELEASES | Rename-Item -NewName { $_.Name -replace 'grafana_kiosk-','grafana-kiosk-x64-' }
          Get-ChildItem .\out\installers\arm64\* -Exclude RELEASES | Rename-Item -NewName { $_.Name -replace 'grafana_kiosk-','grafana-kiosk-arm64-' }
          Get-ChildItem .\out\installers\x64\* -Exclude RELEASES | Move-Item -Destination .\out\installers
          Get-ChildItem .\out\installers\arm64\* -Exclude RELEASES | Move-Item -Destination .\out\installers
      - name: Check Output
        run: ls out/installers
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            out/installers/grafana-kiosk*
